name = "TrixiBottomTopography"
uuid = "86af9953-43df-404b-8eaa-d20d82623a82"
authors = ["maxbertrand1996 <maxbertrand1996@googlemail.com>", "Andrew R. Winters <andrew.ross.winters@liu.se>"]
version = "0.1.2-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GMT = "5752ebe1-31b9-557e-87aa-f909b540aa54"
GeophysicalModelGenerator = "3700c31b-fa53-48a6-808a-ef22d5a84742"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
TrixiBottomTopographyMakieExt = "Makie"

[compat]
CSV = "0.10.15"
CairoMakie = "0.12.18"
DataFrames = "1.7.0"
Downloads = "1.6"
GMT = "1.29.0"
GeophysicalModelGenerator = "0.7.4"
LinearAlgebra = "1"
Makie = "0.21, 0.22"
Plots = "1.40.13"
SparseArrays = "1"
julia = "1.10"
